name: Build Flutter APK

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: تحميل الملفات
        uses: actions/checkout@v6

      - name: فك ملف المشروع
        run: |
          unzip -o suf​ra_flutter_ready.zip -d app
          find app -name pubspec.yaml -print

      - name: تثبيت Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable

      - name: بناء التطبيق
        run: |
          cd app
          flutter pub get
          flutter build apk --release

      - name: حفظ APK
        uses: actions/upload-artifact@v4
        with:
          name: app-release
          path: app/build/app/outputs/flutter-apk/app-release.apk
